project: 
  type: website
  output-dir: docs
  

website: 
  title: "Python Closeread Website"
  navbar: 
    left: 
      - href: python_closeread.qmd
        text: Home
format: 
  closeread-html
  
      